site_name: Excelencia Toastmasters
theme:
  name: material
plugins:
  - gh-admonitions
  - search
  - enumerate-headings
markdown_extensions:
  - attr_list
  - admonition
  - pymdownx.details
  - pymdownx.superfences
